### ISSUE TITLE
Adicionar campo nome no objeto Acoes

### ISSUE THREAD

**Issue by Tavisco** [Tavisco/PI3#1]
Precisamos do nome completo da ação que estamos trabalhando.
Precisamos adicionar este item no banco de dados e no objeto Acoes.
@Julio3Cesar poderia fazer isso?

**Comment by Julio3Cesar** [comment]
Trabalhando nesse item.

**Comment by Julio3Cesar** [comment]
Resolvido item no commit 881ea2ec275735e70676978fccc3ae2961f5c806
